<a href="https://colab.research.google.com/github/TYamashita-22016/M_Math/blob/main/Chap06_Ex_01%262%263.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy.ma.core import cumsum
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
sns.set()
%matplotlib inline
%precision 3

import requests, zipfile
from io import StringIO
import io

from sklearn import linear_model

In [3]:
hier_df1 = DataFrame(
    np.arange(12).reshape((3,4)),
    index = [['c','d','d'],[1,2,1]],
    columns = [
        ['Kyoto','Nagoya','Hokkaido','Kyoto'],
        ['Yellow','Yellow','Red','Blue']
    ]
)

hier_df1.index.names = ['key1','key2']
hier_df1.columns.names = ['city','color']
hier_df1['Kyoto']

color      Yellow  Blue
key1 key2
c    1          0     3
d    2          4     7
     1          8    11

In [5]:
hier_df1.groupby('city', axis=1).mean()

city       Hokkaido  Kyoto  Nagoya
key1 key2
c    1          2.0    1.5     1.0
d    2          6.0    5.5     5.0
     1         10.0    9.5     9.0

In [7]:
hier_df1.groupby('key2').sum()

city   Kyoto Nagoya Hokkaido Kyoto
color Yellow Yellow      Red  Blue
key2
1          8     10       12    14
2          4      5        6     7